
build:
	cargo build

clean:
	cargo clean

run: run1 run2

run1:
	cargo run --manifest-path ./dir1/Cargo.toml --
	cargo run --bin dir1

run2:
	cargo run --manifest-path ./dir2/Cargo.toml --
	cargo run --bin dir2



